"""Add debug_data column to SearchRequest

Revision ID: 96c4984b6328
Revises: f283ac1b112a
Create Date: 2026-02-05 20:50:44.969881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c4984b6328'
down_revision: Union[str, Sequence[str], None] = 'f283ac1b112a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_request', sa.Column('debug_data', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_request', 'debug_data')
    # ### end Alembic commands ###
