"""Initial database schema

Revision ID: d9ae22142a7e
Revises: 
Create Date: 2026-02-04 10:08:24.743482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ae22142a7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_request',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'DONE', 'STOPPED', 'ERROR', name='searchstatus'), nullable=False),
    sa.Column('input_source', sa.Enum('MANUAL', 'FILE', name='inputsource'), nullable=False),
    sa.Column('object_name', sa.String(), nullable=True),
    sa.Column('ktru_code', sa.String(), nullable=False),
    sa.Column('okpd2_code', sa.String(), nullable=True),
    sa.Column('customer_region', sa.String(), nullable=False, server_default='СЗФО'),
    sa.Column('law', sa.String(), nullable=False, server_default='44'),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execution_statuses', sa.JSON(), nullable=False, server_default='["Исполнение завершено", "Исполнение прекращено"]'),
    sa.Column('limit_contracts', sa.Integer(), nullable=False, server_default='30'),
    sa.Column('found_total', sa.Integer(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('nmc_value', sa.Float(), nullable=True),
    sa.Column('selected_contract_ids', sa.JSON(), nullable=True, server_default='[]'),
    sa.Column('runtime_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_result',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('search_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reestr_number', sa.String(), nullable=False),
    sa.Column('contract_url', sa.String(), nullable=False),
    sa.Column('sign_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True, server_default='RUB'),
    sa.Column('match_type', sa.Enum('IDENTICAL', 'HOMOGENEOUS', 'NO_MATCH', name='matchtype'), nullable=False),
    sa.Column('ai_score', sa.Integer(), nullable=False),
    sa.Column('manufacturer_target', sa.String(), nullable=True),
    sa.Column('manufacturer_found', sa.String(), nullable=True),
    sa.Column('manufacturer_match', sa.Boolean(), nullable=True),
    sa.Column('is_2025_plus', sa.Boolean(), nullable=False, server_default='0'),
    sa.Column('accepted_for_nmc', sa.Boolean(), nullable=False, server_default='0'),
    sa.Column('raw_data_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['search_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_result_reestr_number'), 'contract_result', ['reestr_number'], unique=False)
    op.create_index(op.f('ix_contract_result_search_id'), 'contract_result', ['search_id'], unique=False)
    op.create_table('spec_comparison_row',
    sa.Column('contract_result_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_value', sa.String(), nullable=True),
    sa.Column('actual_value', sa.String(), nullable=True),
    sa.Column('match_status', sa.Enum('MATCH', 'DIFF', 'UNKNOWN', name='matchstatus'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False, server_default='1.0'),
    sa.ForeignKeyConstraint(['contract_result_id'], ['contract_result.id'], ),
    sa.PrimaryKeyConstraint('contract_result_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spec_comparison_row')
    op.drop_index(op.f('ix_contract_result_search_id'), table_name='contract_result')
    op.drop_index(op.f('ix_contract_result_reestr_number'), table_name='contract_result')
    op.drop_table('contract_result')
    op.drop_table('search_request')
    # ### end Alembic commands ###
