"""Update tables to new schema

Revision ID: de3ca5188717
Revises: 96c4984b6328
Create Date: 2026-02-09 10:10:36.111254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'de3ca5188717'
down_revision: Union[str, Sequence[str], None] = '96c4984b6328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite compatibility, we'll skip type changes and only add/remove columns
    # Type changes would require table recreation which is complex
    
    # Note: price column already exists, so we don't need to add it
    
    # Remove columns that are not in the new schema
    op.drop_column('contract_result', 'currency')
    op.drop_column('contract_result', 'manufacturer_match')
    op.drop_column('contract_result', 'manufacturer_target')
    op.drop_column('contract_result', 'accepted_for_nmc')
    op.drop_column('contract_result', 'manufacturer_found')
    op.drop_column('contract_result', 'created_at')
    
    # Remove columns from search_request that are not in the new schema
    op.drop_column('search_request', 'debug_data')
    op.drop_column('search_request', 'execution_statuses')
    op.drop_column('search_request', 'okpd2_code')
    op.drop_column('search_request', 'error_message')
    op.drop_column('search_request', 'processed_count')
    op.drop_column('search_request', 'date_to')
    op.drop_column('search_request', 'customer_region')
    op.drop_column('search_request', 'date_from')
    op.drop_column('search_request', 'law')
    op.drop_column('search_request', 'found_total')
    op.drop_column('search_request', 'runtime_ms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-add dropped columns
    op.add_column('search_request', sa.Column('runtime_ms', sa.INTEGER(), nullable=True))
    op.add_column('search_request', sa.Column('found_total', sa.INTEGER(), nullable=True))
    op.add_column('search_request', sa.Column('law', sa.VARCHAR(length=50), nullable=False))
    op.add_column('search_request', sa.Column('date_from', sa.DATETIME(), nullable=False))
    op.add_column('search_request', sa.Column('customer_region', sa.VARCHAR(length=200), nullable=False))
    op.add_column('search_request', sa.Column('date_to', sa.DATETIME(), nullable=False))
    op.add_column('search_request', sa.Column('processed_count', sa.INTEGER(), nullable=False))
    op.add_column('search_request', sa.Column('error_message', sa.TEXT(), nullable=True))
    op.add_column('search_request', sa.Column('okpd2_code', sa.VARCHAR(length=100), nullable=True))
    op.add_column('search_request', sa.Column('execution_statuses', sqlite.JSON(), nullable=False))
    op.add_column('search_request', sa.Column('debug_data', sqlite.JSON(), nullable=False))
    
    # Re-add dropped columns to contract_result
    op.add_column('contract_result', sa.Column('created_at', sa.DATETIME(), nullable=False))
    op.add_column('contract_result', sa.Column('manufacturer_found', sa.VARCHAR(length=200), nullable=True))
    op.add_column('contract_result', sa.Column('accepted_for_nmc', sa.BOOLEAN(), nullable=False))
    op.add_column('contract_result', sa.Column('manufacturer_target', sa.VARCHAR(length=200), nullable=True))
    op.add_column('contract_result', sa.Column('manufacturer_match', sa.BOOLEAN(), nullable=True))
    op.add_column('contract_result', sa.Column('currency', sa.VARCHAR(length=10), nullable=False))
    
    # Note: price column already existed, so we don't drop it
    # ### end Alembic commands ###
