"""Initial migration: create search_request, contract_result, and spec_comparison_row tables

Revision ID: f283ac1b112a
Revises: 
Create Date: 2026-02-05 08:50:30.396983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f283ac1b112a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_request',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'DONE', 'STOPPED', 'ERROR', name='searchstatus'), nullable=False),
    sa.Column('input_source', sa.Enum('MANUAL', 'FILE', name='inputsource'), nullable=False),
    sa.Column('object_name', sa.String(length=500), nullable=False),
    sa.Column('ktru_code', sa.String(length=100), nullable=False),
    sa.Column('okpd2_code', sa.String(length=100), nullable=True),
    sa.Column('customer_region', sa.String(length=200), nullable=False),
    sa.Column('law', sa.String(length=50), nullable=False),
    sa.Column('date_from', sa.DateTime(), nullable=False),
    sa.Column('date_to', sa.DateTime(), nullable=False),
    sa.Column('execution_statuses', sa.JSON(), nullable=False),
    sa.Column('limit_contracts', sa.Integer(), nullable=False),
    sa.Column('found_total', sa.Integer(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('nmc_value', sa.Float(), nullable=True),
    sa.Column('selected_contract_ids', sa.JSON(), nullable=False),
    sa.Column('runtime_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_result',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('reestr_number', sa.String(length=100), nullable=False),
    sa.Column('contract_url', sa.String(length=500), nullable=False),
    sa.Column('sign_date', sa.DateTime(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('match_type', sa.Enum('IDENTICAL', 'HOMOGENEOUS', 'NO_MATCH', name='matchtype'), nullable=False),
    sa.Column('ai_score', sa.Integer(), nullable=False),
    sa.Column('manufacturer_target', sa.String(length=200), nullable=True),
    sa.Column('manufacturer_found', sa.String(length=200), nullable=True),
    sa.Column('manufacturer_match', sa.Boolean(), nullable=True),
    sa.Column('is_2025_plus', sa.Boolean(), nullable=False),
    sa.Column('accepted_for_nmc', sa.Boolean(), nullable=False),
    sa.Column('raw_data_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['search_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_result_reestr_number'), 'contract_result', ['reestr_number'], unique=False)
    op.create_table('spec_comparison_row',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_result_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('match_status', sa.Enum('MATCH', 'DIFF', 'UNKNOWN', name='matchstatus'), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_result_id'], ['contract_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spec_comparison_row')
    op.drop_index(op.f('ix_contract_result_reestr_number'), table_name='contract_result')
    op.drop_table('contract_result')
    op.drop_table('search_request')
    # ### end Alembic commands ###
