# Используем официальный образ Maven с JDK
FROM maven:3.9.4-eclipse-temurin-17

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем весь проект в контейнер
COPY . .


# Выполняем сборку и тесты
RUN mvn clean test